### ISSUE TITLE
Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused

### ISSUE THREAD

**Issue by svott03** [zeromicro/zero-doc#163]
Command: go run check.go -f etc/check.yaml

Output:
Starting rpc server at 0.0.0.0:8080...
{"level":"warn","ts":"2022-12-27T19:20:55.154-0800","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x14000290380/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
{"@timestamp":"2022-12-27T19:20:55.155-08:00","caller":"zrpc/server.go:91","content":"context deadline exceeded","level":"error"}
panic: context deadline exceeded

goroutine 1 [running]:
github.com/zeromicro/go-zero/zrpc.(*RpcServer).Start(0x1027e6bc0?)
	{HOME}go/pkg/mod/github.com/zeromicro/go-zero@v1.4.3/zrpc/server.go:92 +0x80
main.main()
	{HOME}/Desktop/myapp/bookstore/rpc/check/check.go:38 +0x228
exit status 2

**Comment by SmartBest-Zhi** [comment]
I have the same problem.

**Comment by Knni9ht** [comment]
同问：
> go run transform.go -f etc/transform.yaml
Starting rpc server at 0.0.0.0:8080...
{"level":"warn","ts":"2025-07-22T17:15:10.005831+0800","logger":"etcd-client","caller":"v3@v3.5.15/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00049c960/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connectex: No connection could be made because the target machine actively refused it.\""}
{"@timestamp":"2025-07-22T17:15:10.006+08:00","caller":"zrpc/server.go:90","content":"context deadline exceeded","level":"error"}
panic: context deadline exceeded

goroutine 1 [running]:
github.com/zeromicro/go-zero/zrpc.(*RpcServer).Start(0x2a8bfe0?)
        C:/Users/Administrator/go/pkg/mod/github.com/zeromicro/go-zero@v1.8.5/zrpc/server.go:91 +0x75
main.main()
        D:/code/go/go-zero-test/shorturl/rpc/transform/transform.go:38 +0x265
exit status 2

**Comment by kevwan** [comment]
etcd in docker? you can verify the access with etcdctl command.
