### ISSUE TITLE
go-zero 1.2.4 version rpc client panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by fengjiannan2010** [zeromicro/zero-doc#79]
### OS info : armv7l GNU/Linux

```
func (l *OdriveLogic) SetOdriveDateTime() (oburn.Message, error) {
	var timeFormat = "2006-01-02 15:04:05"
	dateTime := time.Now().Format(timeFormat)
	logx.Infof("DateTime:%s", dateTime)
	response, err := l.svcCtx.Odrive.SetTime(l.ctx, &odrive.SetTimeRequest{DateTime: dateTime})
	if err != nil {
		l.GrpcError(err)
		logx.Errorf("SetOdriveDateTime Error:%s", err.Error())
		return oburn.Message{}, err
	}
	logx.Infof("SetOdriveDateTime Response:%v", response)
	responseMessage := response.GetMessage()
	return oburn.Message{
		IsSuccess: responseMessage.GetIsSuccess(),
		Code:      responseMessage.GetCode(),
		Message:   responseMessage.GetMessage(),
	}, nil
}
```

### rpc service not runing ,client call func not panic

```
2021/12/03 13:20:00 {"@timestamp":"2021-12-03T13:20:00.232Z","level":"error","content":"cpu_linux.go:29 open cpuacct.usage_percpu: no such file or directory"}
gorm init sqlite3 done.2021/12/03 13:20:00 register table success
{"@timestamp":"2021-12-03T13:20:00.515Z","level":"info","content":"DateTime:2021-12-03 13:20:00"}
Starting restServer at 127.0.0.1:8090
{"@timestamp":"2021-12-03T13:20:00.522Z","level":"info","duration":"0.8ms","content":"fail - direct:/192.168.1.136:9000/odriveclient.Odrive/TestUnityReady -  - rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing dial tcp 192.168.1.136:9000: connect: connection refused\"","trace":"e2a43bd85ce536a3c08b4646e38388c8","span":"113651448091ac85"}
{"@timestamp":"2021-12-03T13:20:00.523Z","level":"error","content":"odrivelogic.go:83 TestUnityReady Error:rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing dial tcp 192.168.1.136:9000: connect: connection refused\""}
```

---

###  rpc service runing ,client call func panic

```
2021/12/03 13:21:38 {"@timestamp":"2021-12-03T13:21:38.373Z","level":"error","content":"cpu_linux.go:29 open cpuacct.usage_percpu: no such file or directory"}
gorm init sqlite3 done.2021/12/03 13:21:38 register table success
{"@timestamp":"2021-12-03T13:21:38.666Z","level":"info","content":"DateTime:2021-12-03 13:21:38"}
Starting restServer at 127.0.0.1:8090
panic: unaligned 64-bit atomic operation [recovered]
	panic: unaligned 64-bit atomic operation

goroutine 30 [running]:
github.com/tal-tech/go-zero/core/breaker.(*googleBreaker).doReq.func1(0x4226980)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/core/breaker/googlebreaker.go:75 +0x74
panic({0x14c94a0, 0x195dd68})
	/usr/local/go1.17.3/src/runtime/panic.go:1038 +0x23c
runtime/internal/atomic.panicUnaligned()
	/usr/local/go1.17.3/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x4027c14, 0x798dd0d94fda4d)
	/usr/local/go1.17.3/src/runtime/internal/atomic/atomic_arm.s:301 +0x14
github.com/tal-tech/go-zero/zrpc/internal/balancer/p2c.(*p2cPicker).choose(0x4204a80, 0x4027bc0, 0x0)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/balancer/p2c/p2c.go:153 +0x1a8
github.com/tal-tech/go-zero/zrpc/internal/balancer/p2c.(*p2cPicker).Pick(0x4204a80, {{0x170c31e, 0x1c}, {0x19895e0, 0x417e768}})
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/balancer/p2c/p2c.go:84 +0xe0
google.golang.org/grpc.(*pickerWrapper).pick(0x40ada88, {0x19895e0, 0x417e768}, 0x1, {{0x170c31e, 0x1c}, {0x19895e0, 0x417e768}})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/picker_wrapper.go:126 +0x288
google.golang.org/grpc.(*ClientConn).getTransport(0x4168dc0, {0x19895e0, 0x417e768}, 0x1, {0x170c31e, 0x1c})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:955 +0x50
google.golang.org/grpc.(*clientStream).newAttemptLocked(0x41da360, 0x0)
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:408 +0x84c
google.golang.org/grpc.newClientStreamWithParams({0x19895c0, 0x4238300}, 0x261a1f0, 0x4168dc0, {0x170c31e, 0x1c}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:298 +0xa10
google.golang.org/grpc.newClientStream.func2({0x19895c0, 0x4238300}, 0x17c90fc)
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:184 +0x7c
google.golang.org/grpc.newClientStream({0x19895c0, 0x4238300}, 0x261a1f0, 0x4168dc0, {0x170c31e, 0x1c}, {0x4010a18, 0x1, 0x1})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:212 +0x3e4
google.golang.org/grpc.invoke({0x19895c0, 0x4238300}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, {0x4010a18, ...})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/call.go:66 +0x60
github.com/tal-tech/go-zero/zrpc/internal/clientinterceptors.TimeoutInterceptor.func1({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, 0x17c90f4, ...)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/clientinterceptors/timeoutinterceptor.go:21 +0x180
google.golang.org/grpc.getChainUnaryInvoker.func1({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, {0x4010a18, ...})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0xd4
github.com/tal-tech/go-zero/zrpc/internal/clientinterceptors.BreakerInterceptor.func1()
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/clientinterceptors/breakerinterceptor.go:17 +0x8c
github.com/tal-tech/go-zero/core/breaker.(*googleBreaker).doReq(0x4226980, 0x4238240, 0x0, 0x446e460)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/core/breaker/googlebreaker.go:79 +0xb4
github.com/tal-tech/go-zero/core/breaker.loggedThrottle.doReq({{0x44ee500, 0x36}, {0x197bd1c, 0x4226980}, 0x42382c0}, 0x4238240, 0x0, 0x17c8d14)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/core/breaker/breaker.go:172 +0xac
github.com/tal-tech/go-zero/core/breaker.(*circuitBreaker).DoWithAcceptable(0x4226910, 0x4238240, 0x17c8d14)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/core/breaker/breaker.go:122 +0x40
github.com/tal-tech/go-zero/core/breaker.DoWithAcceptable.func1({0x19a1ef4, 0x4226910})
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/core/breaker/breakers.go:20 +0x34
github.com/tal-tech/go-zero/core/breaker.do({0x44ee500, 0x36}, 0x4191abc)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/core/breaker/breakers.go:67 +0x40
github.com/tal-tech/go-zero/core/breaker.DoWithAcceptable({0x44ee500, 0x36}, 0x4238240, 0x17c8d14)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/core/breaker/breakers.go:19 +0x5c
github.com/tal-tech/go-zero/zrpc/internal/clientinterceptors.BreakerInterceptor({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, 0x417e6f0, ...)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/clientinterceptors/breakerinterceptor.go:16 +0x21c
google.golang.org/grpc.getChainUnaryInvoker.func1({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, {0x4010a18, ...})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0xd4
github.com/tal-tech/go-zero/zrpc/internal/clientinterceptors.PrometheusInterceptor({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, 0x417e6d8, ...)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/clientinterceptors/prometheusinterceptor.go:40 +0x31c
google.golang.org/grpc.getChainUnaryInvoker.func1({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, {0x4010a18, ...})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0xd4
github.com/tal-tech/go-zero/zrpc/internal/clientinterceptors.DurationInterceptor({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, 0x417e6c0, ...)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/clientinterceptors/durationinterceptor.go:23 +0xfc
google.golang.org/grpc.getChainUnaryInvoker.func1({0x19895e0, 0x417e288}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, {0x4010a18, ...})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0xd4
github.com/tal-tech/go-zero/zrpc/internal/clientinterceptors.UnaryTracingInterceptor({0x1989580, 0x43b2fc0}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, 0x417e258, ...)
	/home/gopath/pkg/mod/github.com/tal-tech/go-zero@v1.2.4/zrpc/internal/clientinterceptors/tracinginterceptor.go:31 +0x190
google.golang.org/grpc.chainUnaryClientInterceptors.func1({0x1989580, 0x43b2fc0}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, 0x4168dc0, 0x17c90f4, ...)
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:344 +0xc8
google.golang.org/grpc.(*ClientConn).Invoke(0x4168dc0, {0x1989580, 0x43b2fc0}, {0x170c31e, 0x1c}, {0x15f0ed0, 0x446e140}, {0x15f0f68, 0x417e240}, {0x0, ...})
	/home/gopath/pkg/mod/google.golang.org/grpc@v1.42.0/call.go:35 +0x130
oburn/client/odrive.(*odriveClient).SetTime(0x406bf18, {0x1989580, 0x43b2fc0}, 0x446e140, {0x0, 0x0, 0x0})
	/home/gowork/oburn/client/odrive/odrive.pb.go:7142 +0x90
oburn/client/odriveclient.(*defaultOdrive).SetTime(0x4010b20, {0x1989580, 0x43b2fc0}, 0x446e140, {0x0, 0x0, 0x0})
	/home/gowork/oburn/client/odriveclient/odrive.go:307 +0x84
oburn/internal/logic/job.(*OdriveLogic).SetOdriveDateTime(0x44fd758)
	/home/gowork/oburn/internal/logic/job/odrivelogic.go:126 +0x140
main.main.func1()
	/home/gowork/oburn/cmd/oburn/oburn.go:63 +0x24
golang.org/x/sync/errgroup.(*Group).Go.func1(0x4181e90, 0x17c9d74)
	/home/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x50

```

# go-zero v1.2.2  version is ok but rpc pb.go:

```
type SetTimeRequest struct {
	DateTime  string   `protobuf:"bytes,1,opt,name=dateTime,proto3" json:"dateTime,omitempty"` //时间 格式 2021-11-11 00:00:00
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

# go-zero v1.2.4 and v1.2.3 version error rpc pb.go is:

```
type SetTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateTime string `protobuf:"bytes,1,opt,name=dateTime,proto3" json:"dateTime,omitempty"` //时间 格式 2021-11-11 00:00:00
}
```

**Comment by fengjiannan2010** [comment]
issues error
